// scripts/genHittingManifest.mjs
import fs from 'fs';
import path from 'node:path';

export const OUT = path.resolve(process.cwd(), 'src/data/logs/hittingManifest.js');
const logsDir = path.resolve(process.cwd(), 'src/data/logs');

const files = fs.readdirSync(logsDir)
  .filter(f => /^hitters-\d{4}-\d{2}-\d{2}\.js$/.test(f))
  .sort(); // chronological by filename

if (!files.length) {
  console.error('[gen:hitting-manifest] No hitters-YYYY-MM-DD.js files found in', logsDir);
  process.exit(1);
}

const importLines = [];
const arrayIds = [];

for (const f of files) {
  // e.g. hitters-2025-06-04.js -> h2025_06_04
  const m = f.match(/^hitters-(\d{4})-(\d{2})-(\d{2})\.js$/);
  if (!m) continue;
  const id = `h${m[1]}_${m[2]}_${m[3]}`;
  importLines.push(`import ${id} from './${f}';`);
  arrayIds.push(id);
}

const content = `// AUTO-GENERATED by scripts/genHittingManifest.mjs
${importLines.join('\n')}

const MANIFEST = [
  ${arrayIds.join(', ')}
];

export default MANIFEST;
`;

fs.writeFileSync(OUT, content);
console.log(`[gen:hitting-manifest] Wrote ${files.length} files to ${OUT}`);
