// scripts/genPitchingManifest.mjs
import fs from 'fs';
import path from 'node:path';

export const OUT = path.resolve(process.cwd(), 'src/data/logs/pitchingManifest.js');
const logsDir = path.resolve(process.cwd(), 'src/data/logs');

const files = fs.readdirSync(logsDir)
  .filter(f => /^pitching-\d{4}-\d{2}-\d{2}\.js$/.test(f))
  .sort(); // chronological by filename

if (!files.length) {
  console.error('[gen:manifest] No pitching-YYYY-MM-DD.js files found in', logsDir);
  process.exit(1);
}

const importLines = [];
const arrayIds = [];

for (const f of files) {
  // e.g. pitching-2025-06-04.js -> p2025_06_04
  const m = f.match(/^pitching-(\d{4})-(\d{2})-(\d{2})\.js$/);
  if (!m) continue;
  const id = `p${m[1]}_${m[2]}_${m[3]}`;
  importLines.push(`import ${id} from './${f}';`);
  arrayIds.push(id);
}

const content = `// AUTO-GENERATED by scripts/genPitchingManifest.mjs
${importLines.join('\n')}

const MANIFEST = [
  ${arrayIds.join(', ')}
];

export default MANIFEST;
`;

fs.writeFileSync(OUT, content);
console.log(`[gen:manifest] Wrote ${files.length} files to ${OUT}`);
